# Generated by Django 3.2.17 on 2023-02-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created',
        ),
    ]
