# Generated by Django 3.2.17 on 2023-02-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20230220_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
