# Generated by Django 3.2.17 on 2023-02-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todo_overdue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created',
        ),
    ]
